"""Originality as part of Product Truth: the IP firewall's publishable half.

Master v1.0, v0.23 sections 78-79 (F-783, F-785, F-791, F-794, F-795, F-798), read through the
Final Build supersession S1: **private, complete reverse-engineering of a purchased pattern is
allowed** (F-789, F-797) -- the teardown laboratory is encouraged to understand a competitor's
garment architecture as deeply as it can. What is forbidden is *publishing* their protected
text or images, or a light derivative of their design. This module is the boundary on the
publishing side, and every check in it is deterministic: an LLM may be asked for an opinion
about similarity, and the answer here wins even if every model disagrees.

Five things live here, each the runtime form of one requirement:

**1. Design provenance is required, not optional (F-783, F-798).** Every Brambleloop-authored
CIR must carry a complete `cir.model.Provenance`: the concept it realises, a digest of the
brief it was built from, the Brambleloop-owned primitives it used (motif library, grading
engine, shaping rules), and the benchmarks it consulted. `provenance_findings` refuses a
release without one. Until 2026-09-28 the record was stamped only on graded garments, so the
rest of the catalogue could be certified with nothing saying where its design came from --
which is the one fact a copyright question asks first.

**2. A competitor-informed design carries a design-difference ledger (F-794), and the ledger
must record a meaningful redesign (F-791).** When provenance lists benchmarks consulted, a
ledger entry per benchmark states what was learned, what Brambleloop changed, why each change
is better and which aspects were designed independently. `redesign_verdict` then refuses a
ledger whose changes are only the superficial ones F-791 names -- colour, yarn, wording, size
labels, button count, small dimensions, a few rows. A ledger is a claim; the classifier below
reads the claim's own words so an honest-looking label ("construction") on a superficial
change ("added two rows") does not pass.

**3. Similarity review before sale (F-795)** compares a candidate against every purchased
benchmark this company holds a fingerprint of -- both commercial benchmarks, the side-to-side
textured cardigan (benchmark 1) and the Mini Star Stitch Cardigan (benchmark 2) -- on four
dimensions: wording n-grams, unusual numeric sequences, distinctive feature combinations and
construction sequence. A dimension with nothing to compare (no benchmark text was ever
fingerprinted) is UNMEASURED, never "no overlap". Material overlap is escalated for redesign
rather than hidden: it is an ERROR finding naming the benchmark and the dimension.

**4. A benchmark or seller image is never a generation reference (F-785).**
`refuse_benchmark_reference` is called by the image gateway's request builder for every
reference image, before a request exists. Competitor photography is for private evaluation.

**5. Fingerprints, never text.** The only representation of a benchmark's wording anywhere in
this system is a set of salted, truncated hashes of its word 6-grams. They can say "these two
documents share 40% of their phrasing" and cannot be turned back into a sentence, which keeps
the rule of `teardown/library.py` -- no table holds a competitor's instructions -- intact.
"""
from __future__ import annotations

import functools
import hashlib
import json
import math
import re
from dataclasses import dataclass, field
from pathlib import Path

from ..cir.compiler import ERROR, WARNING, Finding

# ---------------------------------------------------------------------------
# 1. Design provenance (F-783, F-798)

# Who may be named as a design's author. A design generated by something else -- a model
# paraphrasing a purchased PDF, an unlicensed import -- is not Brambleloop's own work however
# complete the rest of its record is.
OWN_AUTHORS: frozenset[str] = frozenset({"brambleloop"})


def brief_digest(brief: dict) -> str:
    """A stable 16-hex digest of the parameters a design was built from.

    Sorted JSON, so the same brief always gives the same digest and the digest changes exactly
    when the brief does.
    """
    payload = json.dumps(brief, sort_keys=True, default=str)
    return hashlib.sha256(payload.encode()).hexdigest()[:16]


def catalogue_provenance(concept_key: str, brief: dict, primitives: tuple[str, ...]):
    """The provenance a hand-engineered catalogue builder stamps on its CIR (F-783 backfill).

    `benchmarks_consulted` is empty on purpose and by audit: no catalogue builder imports
    `cir.benchmarks` or anything under `research/` (tests/test_cert_design.py and
    tests/test_originality.py hold that), so the honest record is that none was consulted.
    `at` is left unset: a timestamp would make the release hash differ on every build of an
    unchanged design.
    """
    from ..cir.model import Provenance

    return Provenance(concept_key=concept_key, brief_digest=brief_digest(brief),
                      primitives_used=tuple(primitives), benchmarks_consulted=(),
                      generated_by="brambleloop")


def provenance_gaps(prov) -> list[str]:
    """What a provenance record is missing. Empty means complete."""
    if prov is None:
        return ["provenance"]
    gaps = []
    if not str(getattr(prov, "concept_key", "") or "").strip():
        gaps.append("concept_key")
    if not str(getattr(prov, "brief_digest", "") or "").strip():
        gaps.append("brief_digest")
    if not tuple(getattr(prov, "primitives_used", ()) or ()):
        # The primitives are how the design was *made*. A record that names a concept and a
        # brief but no method says what the product is for and not where its numbers came
        # from, which is the half F-783 is about.
        gaps.append("primitives_used")
    if not str(getattr(prov, "generated_by", "") or "").strip():
        gaps.append("generated_by")
    return gaps


def provenance_findings(cir, *, ledger: "list[LedgerEntry] | None" = None) -> list[Finding]:
    """The certificate's originality-provenance stage (F-783, F-798, F-794, F-791).

    A `benchmark` CIR passes through: it is a record of someone else's work, never a product,
    and the specification stage already refuses one relabelled as ours.
    """
    if getattr(cir, "authored", "brambleloop") != "brambleloop":
        return []
    prov = getattr(cir, "provenance", None)
    if prov is None:
        return [Finding(
            ERROR, "PROVENANCE_MISSING",
            f"{cir.slug} is authored as Brambleloop's own but carries no design provenance: "
            f"nothing records the concept, brief, primitives or benchmarks it was built from. "
            f"A product is not release-ready on technical correctness alone (F-798); its "
            f"provenance must show the design is Brambleloop's own work (F-783)")]
    out: list[Finding] = []
    gaps = provenance_gaps(prov)
    if gaps:
        out.append(Finding(
            ERROR, "PROVENANCE_INCOMPLETE",
            f"{cir.slug}'s design provenance is missing {gaps}. Every field is what makes the "
            f"record checkable rather than asserted (F-783)"))
    author = str(getattr(prov, "generated_by", "") or "").strip().lower()
    if author and author not in OWN_AUTHORS:
        out.append(Finding(
            ERROR, "PROVENANCE_NOT_OURS",
            f"{cir.slug}'s provenance names {author!r} as its author; a release authored as "
            f"Brambleloop's must be generated by {sorted(OWN_AUTHORS)} (F-798)"))
    consulted = tuple(getattr(prov, "benchmarks_consulted", ()) or ())
    if consulted:
        entries = ledger if ledger is not None else declared_ledger(prov.concept_key)
        if not entries:
            out.append(Finding(
                ERROR, "DESIGN_LEDGER_MISSING",
                f"{cir.slug} consulted benchmarks {list(consulted)} and has no "
                f"design-difference ledger: what was learned, what changed, why it is better "
                f"and what was designed independently must be recorded (F-794)"))
        else:
            verdict = redesign_verdict(entries, consulted)
            if not verdict["passed"]:
                out.append(Finding(
                    ERROR, "REDESIGN_NOT_MEANINGFUL",
                    f"{cir.slug}: " + "; ".join(verdict["reasons"][:4]) + " (F-791)"))
    return out


# ---------------------------------------------------------------------------
# 2. The design-difference ledger (F-794) and the meaningful-redesign gate (F-791)

# Aspects whose change distinguishes a product materially (F-790's improvement list, less the
# ones F-791 names as insufficient on their own).
MATERIAL_ASPECTS: tuple[str, ...] = (
    "fit", "proportions", "stitch_system", "shaping", "construction", "grading", "sizing",
    "features", "finishing", "silhouette",
)
# F-791, verbatim in vocabulary: "merely changing colour, yarn, wording, size labels, button
# count, small dimensions or a few rows is not sufficient".
SUPERFICIAL_ASPECTS: tuple[str, ...] = (
    "colour", "yarn", "wording", "size_labels", "button_count", "small_dimensions", "few_rows",
)
# A dimension change below this is a small dimension whatever it is labelled.
SMALL_DIMENSION_PCT = 10.0
# A row-count change at or below this is "a few rows" whatever it is labelled.
FEW_ROWS = 4
# How many material decisions, in how many distinct aspects, a competitor-informed design needs.
MIN_MATERIAL_DECISIONS = 2
MIN_MATERIAL_ASPECTS = 2
MIN_WHY_WORDS = 4

_SUPERFICIAL_WORDS = re.compile(
    r"\b(colou?rs?|colou?rway|palette|shade|hue|yarn|fibre|fiber|brand|wording|reworded|"
    r"rephrased|renamed|label|labels|button|buttons|a few rows|rows? (?:added|removed)|"
    r"(?:added|removed|dropped) (?:one|two|three|four|\d) rows?|slightly|a little)\b")
_MATERIAL_WORDS = re.compile(
    r"\b(fit|ease|proportion|proportions|stitch system|stitch pattern|texture|construction|"
    r"constructed|top-down|bottom-up|side-to-side|in the round|seamless|seamed|raglan|yoke|"
    r"set-in|drop-shoulder|shaping|shaped|decrease|increase|grading|graded|size range|"
    r"body table|silhouette|hood|pocket|collar|closure|placket|finishing|edging|feature|"
    r"features|cropped|oversized|length)\b")


@dataclass
class LedgerEntry:
    """One benchmark's line in a design-difference ledger (F-794)."""

    benchmark_ref: str
    learned: str
    # Each change: {"aspect": one of MATERIAL_ASPECTS or SUPERFICIAL_ASPECTS, "what": str,
    # optional "magnitude_pct": float (dimension changes), optional "rows_delta": int}.
    changed: list[dict] = field(default_factory=list)
    why_better: str = ""
    independent_aspects: list[str] = field(default_factory=list)

    @staticmethod
    def from_dict(d: dict) -> "LedgerEntry":
        return LedgerEntry(benchmark_ref=str(d.get("benchmark_ref") or ""),
                           learned=str(d.get("learned") or ""),
                           changed=[dict(c) for c in (d.get("changed") or [])],
                           why_better=str(d.get("why_better") or ""),
                           independent_aspects=[str(a) for a in
                                                (d.get("independent_aspects") or [])])

    def to_dict(self) -> dict:
        return {"benchmark_ref": self.benchmark_ref, "learned": self.learned,
                "changed": [dict(c) for c in self.changed], "why_better": self.why_better,
                "independent_aspects": list(self.independent_aspects)}


def classify_change(change: dict) -> tuple[str, str]:
    """(effective aspect, "material" | "superficial" | "unclassified") for one change.

    The label is the designer's claim; the classification is this function's. A change
    labelled material is demoted when its own magnitude or wording says otherwise.
    """
    aspect = str(change.get("aspect") or "").strip().lower()
    what = str(change.get("what") or "").lower()
    if aspect in SUPERFICIAL_ASPECTS:
        return aspect, "superficial"
    if aspect not in MATERIAL_ASPECTS:
        return aspect or "unstated", "unclassified"
    pct = change.get("magnitude_pct")
    if pct is not None and abs(float(pct)) < SMALL_DIMENSION_PCT:
        return "small_dimensions", "superficial"
    rows = change.get("rows_delta")
    if rows is not None and abs(int(rows)) <= FEW_ROWS and pct is None:
        return "few_rows", "superficial"
    if _SUPERFICIAL_WORDS.search(what) and not _MATERIAL_WORDS.search(what):
        return aspect, "superficial"
    if not what.strip():
        return aspect, "unclassified"
    return aspect, "material"


def redesign_verdict(entries, consulted=()) -> dict:
    """Whether a ledger documents original design decisions that materially distinguish the
    product from every benchmark consulted (F-791). Deterministic; never asks a model."""
    rows = [e if isinstance(e, LedgerEntry) else LedgerEntry.from_dict(e) for e in entries]
    reasons: list[str] = []
    per_benchmark: dict[str, dict] = {}
    by_ref = {e.benchmark_ref: e for e in rows}
    for ref in consulted:
        if ref not in by_ref:
            reasons.append(f"benchmark {ref!r} was consulted and has no ledger entry")
    for e in rows:
        where = e.benchmark_ref or "unnamed benchmark"
        material, superficial, unclassified = [], [], []
        for c in e.changed:
            aspect, kind = classify_change(c)
            {"material": material, "superficial": superficial,
             "unclassified": unclassified}[kind].append(aspect)
        if not e.benchmark_ref:
            reasons.append("a ledger entry names no benchmark_ref")
        if not e.learned.strip():
            reasons.append(f"{where}: nothing recorded as learned")
        if len(e.why_better.split()) < MIN_WHY_WORDS:
            reasons.append(f"{where}: why_better does not say why the changes improve it")
        if not e.independent_aspects:
            reasons.append(f"{where}: no aspect recorded as independently designed")
        if len(material) < MIN_MATERIAL_DECISIONS or len(set(material)) < MIN_MATERIAL_ASPECTS:
            reasons.append(
                f"{where}: {len(material)} material change(s) in {sorted(set(material))}; "
                f"needs {MIN_MATERIAL_DECISIONS} in {MIN_MATERIAL_ASPECTS}+ of "
                f"{list(MATERIAL_ASPECTS)}. Superficial only: {sorted(superficial)} -- colour, "
                f"yarn, wording, size labels, button count, small dimensions or a few rows "
                f"do not distinguish a design")
        if unclassified:
            reasons.append(f"{where}: changes with no recognised aspect or description: "
                           f"{sorted(unclassified)}")
        per_benchmark[where] = {"material": sorted(material), "superficial": sorted(superficial),
                                "unclassified": sorted(unclassified)}
    if not rows:
        reasons.append("the ledger is empty")
    return {"passed": not reasons, "reasons": reasons, "per_benchmark": per_benchmark}


# Code-declared ledgers, keyed by concept key. A competitor-informed catalogue design declares
# its ledger here, next to nothing else, so the ledger is versioned and reviewed with the code.
# Empty today: no catalogue design consulted a benchmark (see `catalogue_provenance`).
DECLARED_LEDGERS: dict[str, tuple[LedgerEntry, ...]] = {}


def declared_ledger(concept_key: str) -> list[LedgerEntry]:
    return list(DECLARED_LEDGERS.get(concept_key or "", ()))


LEDGER_ACTION = "originality.ledger_recorded"


def record_ledger(db, concept_key: str, entries, *, recorded_by: str = "creative_director"
                  ) -> dict:
    """Persist a concept's ledger (one row per benchmark) with the gate's verdict on it."""
    from datetime import datetime, timezone

    from sqlalchemy import select

    from ..core.models import DesignDifferenceLedger

    rows = [e if isinstance(e, LedgerEntry) else LedgerEntry.from_dict(e) for e in entries]
    verdict = redesign_verdict(rows)
    with db.session() as s:
        for e in rows:
            row = s.scalar(select(DesignDifferenceLedger).where(
                DesignDifferenceLedger.concept_key == concept_key,
                DesignDifferenceLedger.benchmark_ref == e.benchmark_ref))
            if row is None:
                row = DesignDifferenceLedger(concept_key=concept_key,
                                             benchmark_ref=e.benchmark_ref)
                s.add(row)
            row.learned = e.learned
            row.changed = [dict(c) for c in e.changed]
            row.why_better = e.why_better
            row.independent_aspects = list(e.independent_aspects)
            row.verdict = verdict["per_benchmark"].get(e.benchmark_ref or "unnamed benchmark",
                                                       {})
            row.passed = bool(verdict["passed"])
            row.recorded_by = recorded_by
            row.recorded_at = datetime.now(timezone.utc)
    return verdict


def ledger_from_db(db, concept_key: str) -> list[LedgerEntry]:
    from sqlalchemy import select

    from ..core.models import DesignDifferenceLedger

    with db.session() as s:
        return [LedgerEntry(benchmark_ref=r.benchmark_ref, learned=r.learned or "",
                            changed=list(r.changed or []), why_better=r.why_better or "",
                            independent_aspects=list(r.independent_aspects or []))
                for r in s.scalars(select(DesignDifferenceLedger).where(
                    DesignDifferenceLedger.concept_key == concept_key))]


# ---------------------------------------------------------------------------
# 3. Similarity review before sale (F-795)

SHINGLE_WORDS = 6
# Salt so the stored hashes are this system's and not a lookup table for anyone else's.
_SHINGLE_SALT = b"brambleloop-originality-v1"
_WORD = re.compile(r"[a-z0-9]+")
_NUMBER = re.compile(r"\d+")

# Escalation thresholds. Chosen against the whole catalogue (tests/test_originality.py asserts
# no catalogue product escalates against either benchmark) and against synthetic copies.
WORDING_MATERIAL = 0.20          # share of OUR shingles found in the benchmark's
WORDING_MIN_SHARED = 20
FEATURE_MATERIAL = 0.60          # share of the benchmark's distinctive features we also have
FEATURE_MIN_SHARED = 3
CONSTRUCTION_MATERIAL = 0.70     # LCS of construction steps / benchmark's step count
NUMERIC_MIN_RUN = 5              # contiguous run of a benchmark's unusual sequence in our text
# Of one benchmark size's piece-level numbers, how many must recur among ours: at least this
# many, and at least this share of them. Four numbers in the right pieces is a coincidence
# nobody arrives at independently; three is arithmetic anybody might.
PIECE_NUMBERS_MIN = 4
PIECE_NUMBERS_SHARE = 0.75
UNUSUAL_FLOOR = 13               # numbers below this are too common to identify anything


def shingles(text: str, n: int = SHINGLE_WORDS) -> frozenset[str]:
    """Salted, truncated hashes of the word n-grams of `text`. Irreversible by design."""
    words = _WORD.findall((text or "").lower())
    out = set()
    for i in range(len(words) - n + 1):
        gram = " ".join(words[i:i + n]).encode()
        out.add(hashlib.sha256(_SHINGLE_SALT + gram).hexdigest()[:12])
    return frozenset(out)


def _is_arithmetic(seq) -> bool:
    d = {b - a for a, b in zip(seq, seq[1:])}
    return len(d) <= 1


@dataclass
class BenchmarkFingerprint:
    """What the similarity review compares against. Numbers, vocabulary keys and hashes."""

    ref: str
    title: str
    features: frozenset[str] = frozenset()
    construction: tuple[str, ...] = ()
    # Across-size sequences of one measurement, as a grader writes them. Only the unusual ones
    # (not arithmetic progressions) identify a pattern; `unusual_sequences` filters.
    size_sequences: dict[str, tuple[int, ...]] = field(default_factory=dict)
    # Per size, the piece-level numbers a maker works (foundations, piece totals).
    piece_numbers: dict[str, tuple[int, ...]] = field(default_factory=dict)
    wording: frozenset[str] = frozenset()

    def unusual_sequences(self) -> dict[str, tuple[int, ...]]:
        return {k: v for k, v in self.size_sequences.items()
                if len(v) >= NUMERIC_MIN_RUN and not _is_arithmetic(v)}


# Benchmark 2, the Mini Star Stitch Cardigan (MJ's Off The Hook Designs; personal-use licence,
# see `teardown.licence.KNOWN_LICENCES`). Encoded from Brambleloop's own private functional
# reconstruction (research/bench2, F-789): per-size counts are facts about how the garment is
# made, and they are held here only as the comparison set. No wording, chart or image of the
# pattern is in this repository.
_B2_SIZES = ("0-3m", "3-6m", "6-12m", "12-18m", "2-3T", "4", "6", "8", "10", "12")
_B2 = {
    "back_sts": (42, 46, 50, 54, 58, 62, 66, 70, 74, 78),
    "sleeve_chain": (20, 22, 24, 26, 30, 34, 38, 42, 46, 50),
    "yoke_sts": (82, 90, 98, 106, 118, 130, 142, 154, 166, 178),
    "neck_sts": (18, 18, 22, 22, 22, 26, 26, 26, 30, 30),
    "front_right_final_sts": (38, 42, 46, 50, 56, 62, 68, 74, 78, 84),
    "front_panel_sts": (18, 20, 22, 24, 26, 28, 30, 32, 32, 34),
    "hood_row1_sts": (26, 30, 34, 38, 42, 46, 46, 50, 54, 58),
    "hood_width_sts": (36, 40, 46, 50, 56, 60, 60, 64, 70, 74),
    "cuff_sts": (18, 18, 20, 22, 24, 26, 28, 30, 32, 36),
    "band_rows": (38, 42, 46, 50, 54, 58, 62, 66, 70, 74),
}
BENCHMARK_2 = BenchmarkFingerprint(
    ref="benchmark-2-mini-star-stitch-cardigan",
    title="Mini Star Stitch Cardigan (commercial benchmark 2)",
    features=frozenset({"cardigan", "star_stitch_body", "hood", "built_in_sleeves",
                        "blo_ribbed_bands", "buttons", "one_piece_body", "child_sizing"}),
    construction=("hem_band", "back_body", "yoke_with_sleeves", "neck_opening", "fronts",
                  "hood", "cuffs", "collar_band", "buttons"),
    size_sequences=dict(_B2),
    piece_numbers={size: tuple(sorted({_B2[k][i] for k in _B2 if _B2[k][i] >= UNUSUAL_FLOOR}))
                   for i, size in enumerate(_B2_SIZES)},
)


@functools.lru_cache(maxsize=1)
def _benchmark_1() -> BenchmarkFingerprint:
    """Benchmark 1, the side-to-side textured cardigan, from `cir.benchmarks` (read-only).

    Its construction and piece numbers are read off its own encoded CIRs with the same
    functions that read a candidate, so both sides of the comparison speak one vocabulary.
    """
    from ..cir import benchmarks as B

    seqs = {"body_sts": B.BODY_STS, "front_rows": B.FRONT_ROWS, "back_rows": B.BACK_ROWS,
            "armhole_ch": B.ARMHOLE_CH, "sleeve_sts": B.SLEEVE_STS,
            "sleeve_rows": B.SLEEVE_ROWS}
    cirs = {size: B.cardigan(size) for size in B.SIZES}
    return BenchmarkFingerprint(
        ref="benchmark-1-side-to-side-cardigan",
        title="Side-to-side textured cardigan (commercial benchmark 1)",
        features=frozenset({"cardigan", "side_to_side_grain", "one_piece_body",
                            "bridged_armholes", "loop_alternating_texture",
                            "integral_edge_rib", "patch_pockets", "sewn_sleeves"}),
        construction=candidate_construction(cirs[B.SIZES[0]]),
        size_sequences={k: tuple(v) for k, v in seqs.items()},
        piece_numbers={size: tuple(sorted(candidate_piece_numbers(c)))
                       for size, c in cirs.items()})


def code_benchmarks() -> list[BenchmarkFingerprint]:
    """Every purchased benchmark encoded in code. Both, not only the first (F-795)."""
    return [_benchmark_1(), BENCHMARK_2]


def fingerprints_from_db(db) -> list[BenchmarkFingerprint]:
    """Fingerprints captured at teardown (`teardown.reader.read(..., db=)`)."""
    from sqlalchemy import select

    from ..core.models import BenchmarkFingerprintRecord

    with db.session() as s:
        return [BenchmarkFingerprint(
            ref=r.benchmark_ref, title=r.title or r.benchmark_ref,
            features=frozenset(r.features or []), construction=tuple(r.construction or []),
            size_sequences={k: tuple(v) for k, v in (r.size_sequences or {}).items()},
            piece_numbers={k: tuple(v) for k, v in (r.piece_numbers or {}).items()},
            wording=frozenset(r.wording_shingles or []))
            for r in s.scalars(select(BenchmarkFingerprintRecord))]


def record_fingerprint(db, ref: str, *, title: str = "", text: str | None = None,
                       features=(), construction=(), size_sequences=None,
                       piece_numbers=None, source: str = "teardown") -> dict:
    """Store a benchmark's fingerprint. `text` is hashed here and never stored."""
    from datetime import datetime, timezone

    from sqlalchemy import select

    from ..core.models import BenchmarkFingerprintRecord

    hashed = sorted(shingles(text)) if text else None
    with db.session() as s:
        row = s.scalar(select(BenchmarkFingerprintRecord).where(
            BenchmarkFingerprintRecord.benchmark_ref == ref))
        if row is None:
            row = BenchmarkFingerprintRecord(benchmark_ref=ref)
            s.add(row)
        row.title = title or row.title or ref
        if hashed is not None:
            row.wording_shingles = hashed
        if features:
            row.features = sorted(features)
        if construction:
            row.construction = list(construction)
        if size_sequences:
            row.size_sequences = {k: list(v) for k, v in size_sequences.items()}
        if piece_numbers:
            row.piece_numbers = {k: list(v) for k, v in piece_numbers.items()}
        row.source = source
        row.updated_at = datetime.now(timezone.utc)
        return {"ref": ref, "wording_shingles": len(row.wording_shingles or [])}


# --- what a candidate looks like on the same four axes -----------------------

_STAR = {"beg_star_st", "star_st", "end_star_st"}


def _ops(nodes):
    for n in nodes or ():
        inner = getattr(n, "ops", None)
        if inner is not None:
            yield ("repeat", n)
            yield from _ops(inner)
        else:
            yield ("op", n)


def candidate_features(cir) -> frozenset[str]:
    """The candidate's distinctive features, in the benchmarks' vocabulary."""
    names = " ".join(c.name.lower() for c in cir.components)
    title = f"{cir.slug} {cir.title}".lower()
    feats: set[str] = set()
    if "cardigan" in title:
        feats.add("cardigan")
    if "hood" in names:
        feats.add("hood")
    if "pocket" in names:
        feats.add("patch_pockets")
    if "button" in names or any("button" in (m.name or "").lower() for m in cir.materials):
        feats.add("buttons")
    if any(getattr(c, "grain", "up") == "across" for c in cir.components):
        feats.add("side_to_side_grain")
    if "sleeve" in names and any("sleeve" in (s.piece_a + s.piece_b).lower()
                                 for s in cir.assembly):
        feats.add("sewn_sleeves")
    if "yoke" in names and "sleeve" not in names:
        feats.add("built_in_sleeves")
    body_pieces = [c for c in cir.components if "body" in c.name.lower()]
    if len(body_pieces) == 1 and "cardigan" in title:
        feats.add("one_piece_body")
    if "child" in title or "baby" in title or "mini" in title:
        feats.add("child_sizing")
    for comp in cir.components:
        for row in comp.rows:
            kinds = list(_ops(row.ops))
            stitches = {getattr(n, "stitch", None) for k, n in kinds if k == "op"}
            if stitches & _STAR:
                feats.add("star_stitch_body")
            if any(getattr(n, "spans", 0) for k, n in kinds if k == "op"):
                feats.add("bridged_armholes")
            for k, n in kinds:
                if k == "repeat":
                    loops = {getattr(o, "loop", "both") for o in n.ops
                             if getattr(o, "stitch", None)}
                    if {"front", "back"} <= loops:
                        feats.add("loop_alternating_texture")
            back_runs = [n for k, n in kinds if k == "op" and getattr(n, "loop", "") == "back"
                         and getattr(n, "count", 1) >= 5]
            if back_runs and len(kinds) > 1 and "body" in comp.name.lower():
                feats.add("integral_edge_rib")
            if back_runs and any(w in comp.name.lower() for w in
                                 ("band", "cuff", "collar", "rib", "hem")):
                feats.add("blo_ribbed_bands")
    return frozenset(feats)


# Component-name words -> the construction vocabulary the benchmarks are written in.
_STEP_WORDS: tuple[tuple[str, str], ...] = (
    ("hem", "hem_band"), ("pocket", "pockets"), ("hood", "hood"), ("cuff", "cuffs"),
    ("collar", "collar_band"), ("neck", "neck_band"), ("yoke", "yoke_with_sleeves"),
    ("sleeve", "sleeves"), ("front", "fronts"), ("back", "back_body"), ("button", "buttons"),
    ("body", "body"), ("armhole", "armhole"),
)


def candidate_construction(cir) -> tuple[str, ...]:
    steps: list[str] = []
    for comp in cir.components:
        low = comp.name.lower()
        for word, step in _STEP_WORDS:
            if word in low:
                if not steps or steps[-1] != step:
                    steps.append(step)
                break
    return tuple(steps)


def _lcs(a, b) -> int:
    prev = [0] * (len(b) + 1)
    for x in a:
        cur = [0]
        for j, y in enumerate(b):
            cur.append(prev[j] + 1 if x == y else max(prev[j + 1], cur[j]))
        prev = cur
    return prev[-1]


def candidate_piece_numbers(cir) -> frozenset[int]:
    """Piece-level numbers: each piece's foundation and its first, last and widest count."""
    from ..cir.compiler import compile_cir

    result = compile_cir(cir)
    out: set[int] = set()
    for comp in cir.components:
        produced = [r.produced for r in result.rows if r.component == comp.name
                    and r.produced is not None]
        for v in [comp.foundation] + ([produced[0], produced[-1], max(produced)]
                                      if produced else []):
            if v and v >= UNUSUAL_FLOOR:
                out.add(int(v))
    return frozenset(out)


def _contains_run(stream: list[int], seq: tuple[int, ...], run: int) -> bool:
    if len(seq) < run:
        return False
    windows = {tuple(seq[i:i + run]) for i in range(len(seq) - run + 1)
               if not _is_arithmetic(seq[i:i + run])}
    if not windows:
        return False
    for i in range(len(stream) - run + 1):
        if tuple(stream[i:i + run]) in windows:
            return True
    return False


def compare(cir, benchmark: BenchmarkFingerprint, *, pattern_text: str | None = None) -> dict:
    """One candidate against one benchmark, dimension by dimension."""
    dims: dict[str, dict] = {}

    # Wording n-grams. Unmeasured when either side has no text: absence of a fingerprint is
    # not evidence of absence of copying.
    ours = shingles(pattern_text or "") if pattern_text else frozenset()
    if not benchmark.wording or not ours:
        dims["wording"] = {"verdict": "unmeasured",
                           "why": ("no fingerprint of the benchmark's wording has been "
                                   "captured" if not benchmark.wording else
                                   "no candidate text to compare")}
    else:
        shared = len(ours & benchmark.wording)
        share = shared / len(ours)
        dims["wording"] = {"verdict": ("material" if share >= WORDING_MATERIAL
                                       and shared >= WORDING_MIN_SHARED else "clear"),
                           "shared_shingles": shared, "share_of_ours": round(share, 3)}

    # Unusual numeric sequences: a benchmark's non-arithmetic across-size run in our text, or
    # most of one size's piece-level numbers in our pieces.
    hits: list[str] = []
    stream = [int(n) for n in _NUMBER.findall(pattern_text or "")]
    for name, seq in benchmark.unusual_sequences().items():
        if stream and _contains_run(stream, seq, NUMERIC_MIN_RUN):
            hits.append(f"across-size {name} run")
    mine = candidate_piece_numbers(cir)
    for size, nums in benchmark.piece_numbers.items():
        found = sorted(set(nums) & mine)
        need = max(PIECE_NUMBERS_MIN, math.ceil(PIECE_NUMBERS_SHARE * len(set(nums))))
        if len(found) >= need:
            hits.append(f"size {size} piece numbers {found}")
    dims["numeric"] = {"verdict": "material" if hits else "clear", "hits": hits[:6]}

    # Distinctive feature combination.
    feats = candidate_features(cir)
    shared_f = sorted(feats & benchmark.features)
    share_f = len(shared_f) / len(benchmark.features) if benchmark.features else 0.0
    feature_material = share_f >= FEATURE_MATERIAL and len(shared_f) >= FEATURE_MIN_SHARED
    dims["features"] = {"verdict": "material" if feature_material else "clear",
                        "shared": shared_f, "share_of_theirs": round(share_f, 3)}

    # Construction sequence.
    steps = candidate_construction(cir)
    lcs = _lcs(steps, benchmark.construction) if benchmark.construction else 0
    share_c = lcs / len(benchmark.construction) if benchmark.construction else 0.0
    dims["construction"] = {"verdict": "material" if share_c >= CONSTRUCTION_MATERIAL
                            else "clear", "ours": list(steps),
                            "share_of_theirs": round(share_c, 3)}

    # Features and construction together are what "the same design" means; either alone is a
    # genre (every cardigan has fronts and sleeves). Wording or numbers alone are a copy.
    material = [d for d in ("wording", "numeric") if dims[d]["verdict"] == "material"]
    if feature_material and dims["construction"]["verdict"] == "material":
        material += ["features", "construction"]
    return {"benchmark": benchmark.ref, "title": benchmark.title, "dimensions": dims,
            "material": material,
            "unmeasured": [d for d, v in dims.items() if v["verdict"] == "unmeasured"]}


SIMILARITY_ACTION = "originality.similarity_review"


def similarity_review(cir, *, pattern_text: str | None = None, db=None,
                      benchmarks: list[BenchmarkFingerprint] | None = None) -> dict:
    """Compare a candidate with every purchased benchmark (F-795).

    `escalate` is True when any benchmark overlaps materially; the product goes back for
    redesign with the benchmarks and dimensions named. Benchmarks are the code-encoded pair,
    plus every teardown fingerprint in `db` when one is given (a stored fingerprint for the
    same ref adds its wording to the code one rather than replacing it).
    """
    pool = {b.ref: b for b in (benchmarks if benchmarks is not None else code_benchmarks())}
    if db is not None and benchmarks is None:
        for fp in fingerprints_from_db(db):
            have = pool.get(fp.ref)
            if have is None:
                pool[fp.ref] = fp
            else:
                have.wording = have.wording | fp.wording
    comparisons = [compare(cir, b, pattern_text=pattern_text) for b in pool.values()]
    escalated = [c for c in comparisons if c["material"]]
    return {"slug": cir.slug, "benchmarks_compared": sorted(pool),
            "escalate": bool(escalated),
            "escalated": [{"benchmark": c["benchmark"], "dimensions": c["material"]}
                          for c in escalated],
            "unmeasured": sorted({f"{c['benchmark']}:{d}" for c in comparisons
                                  for d in c["unmeasured"]}),
            "comparisons": comparisons}


def similarity_findings(cir, *, pattern_text: str | None = None) -> list[Finding]:
    """The certificate's similarity stage: material overlap is an ERROR, never a footnote."""
    if getattr(cir, "authored", "brambleloop") != "brambleloop":
        return []
    review = similarity_review(cir, pattern_text=pattern_text)
    out = [Finding(ERROR, "SIMILARITY_ESCALATED",
                   f"{cir.slug} overlaps materially with {e['benchmark']} on "
                   f"{e['dimensions']}: escalated for redesign (F-795). A purchased benchmark "
                   f"informs research; the sellable design must be Brambleloop's own")
           for e in review["escalated"]]
    prov = getattr(cir, "provenance", None)
    if prov is not None and tuple(prov.benchmarks_consulted or ()) and review["unmeasured"]:
        # Only for a competitor-informed design: there the unmeasured wording comparison is
        # the one a reviewer most needs to know was not made.
        out.append(Finding(WARNING, "SIMILARITY_UNMEASURED",
                           f"{cir.slug}: not compared on {review['unmeasured'][:4]}; "
                           f"capture the benchmark's wording fingerprint at teardown"))
    return out


def release_findings(cir, *, pattern_text: str | None = None) -> list[Finding]:
    """Everything this module contributes to a release certificate, in one call."""
    return provenance_findings(cir) + similarity_findings(cir, pattern_text=pattern_text)


# ---------------------------------------------------------------------------
# 4. Generation references (F-785)

# Path components that mark a file as somebody else's picture of their own work, or as a
# private reconstruction of a benchmark: the quarantine, seller/designer photography, and the
# research benchmarks' working directories.
_BENCHMARK_PATH_PARTS: frozenset[str] = frozenset({
    "benchmark_library", "seller_photos", "designer_photos", "competitor_photos",
    "benchmark_photos", "bench1", "bench2",
})
_BENCHMARK_NAME = re.compile(r"(seller|designer|competitor|benchmark)[-_ ]?(photo|image|img)",
                             re.I)


class ReferenceRefused(PermissionError):
    """A benchmark or seller image offered as a generation reference."""


def refuse_benchmark_reference(reference: str, *, env: dict[str, str] | None = None,
                               benchmark_hashes: set[str] | frozenset[str] | None = None
                               ) -> None:
    """Refuse a reference image whose provenance is a benchmark or a seller (F-785).

    Three independent tests, any one of which refuses: the file resolves inside the benchmark
    library's quarantine; its path or name marks it as seller/designer/competitor photography
    or a benchmark reconstruction; its bytes hash to a file recorded in a purchase manifest.
    """
    from ..teardown.library import library_root

    ref = str(reference or "")
    path = Path(ref)
    try:
        resolved = path.resolve()
    except (OSError, RuntimeError):
        resolved = path
    root = library_root(env)
    if resolved == root or root in resolved.parents:
        raise ReferenceRefused(
            f"{ref!r} is inside the benchmark library. A purchased pattern's images are for "
            f"private evaluation and are never a generation reference for Brambleloop "
            f"imagery (F-785)")
    parts = {p.lower() for p in resolved.parts} | {p.lower() for p in path.parts}
    marked = parts & _BENCHMARK_PATH_PARTS
    if marked or _BENCHMARK_NAME.search(path.name):
        raise ReferenceRefused(
            f"{ref!r} is marked as benchmark or seller imagery "
            f"({sorted(marked) or path.name}); a competitor's photograph may be studied and "
            f"never conditions a Brambleloop render (F-785)")
    if benchmark_hashes and resolved.is_file():
        digest = hashlib.sha256(resolved.read_bytes()).hexdigest()
        if digest in benchmark_hashes:
            raise ReferenceRefused(
                f"{ref!r} is byte-identical to a file in a benchmark purchase manifest "
                f"(sha256 {digest[:12]}); renamed benchmark imagery is still benchmark "
                f"imagery (F-785)")


def benchmark_file_hashes(db) -> frozenset[str]:
    """Every file hash in every purchase manifest (`BenchmarkProduct.files`)."""
    from sqlalchemy import select

    from ..core.models import BenchmarkProduct

    with db.session() as s:
        return frozenset(f.get("sha256") for r in s.scalars(select(BenchmarkProduct))
                         for f in (r.files or []) if f.get("sha256"))
