"""Turning the existing catalogue into concepts, so the gate can be pointed at our own work.

The owner's judgement is that the generated catalogue's creativity is materially below the
required standard, and the useful response is not agreement — it is a measurement that says
where the shortfall comes from and would notice if it were fixed.

Reading `products/builder.py` as a description of an idea is instructive. A `Design` is a
motif, a palette, a width and a repeat count. There is no field for who the product is for,
what occasion it belongs to, what it does for its owner, or how it is constructed — because
every design is constructed the same way. The generator is not producing weak ideas; it has no
representation of an idea to produce.

So this mapping is deliberately literal. Where a `Design` carries a value, it is used. Where it
carries nothing, the concept records the default the generator effectively assumes, rather than
an interpretation invented here to make the result look better or worse. The verdict that
follows is then a measurement of the generator, not an opinion about it.
"""
from __future__ import annotations

from .concept import Concept

# What the slug reveals about the object, since the design record itself does not say. These
# are read from the product's own name, which is the only place the intent was ever written.
_FORM_HINTS: tuple[tuple[str, str], ...] = (
    ("garland", "garland"),
    ("ornament", "ornament"),
    ("wall-hanging", "wall_hanging"),
    ("runner", "runner"),
    ("placemat", "coaster"),
    ("coaster", "coaster"),
    ("basket", "basket"),
    ("mat", "flat_panel"),
    ("blanket", "rectangle_throw"),
    ("throw", "rectangle_throw"),
    ("graphghan", "rectangle_throw"),
    ("motifs", "flat_panel"),
)

# Occasions a slug actually declares. Anything else is `everyday`, which is what the generator
# assumed by never asking.
_OCCASION_HINTS: tuple[tuple[str, str], ...] = (
    ("spooky", "halloween"),
    ("halloween", "halloween"),
    ("valentine", "valentines"),
    ("nordic-star", "christmas"),
    ("winter-village", "christmas"),
    ("harvest", "thanksgiving"),
    ("autumn", "thanksgiving"),
    ("baby", "new_baby"),
)

_RECIPIENT_HINTS: tuple[tuple[str, str], ...] = (
    ("baby", "new_parent"),
    ("pet", "pet_owner"),
)


def _match(slug: str, hints: tuple[tuple[str, str], ...], default: str) -> str:
    for needle, value in hints:
        if needle in slug:
            return value
    return default


def concept_from_design(design) -> Concept:
    """Map a generated `Design` onto the concept vocabulary, literally.

    Every field the generator does not carry is filled with the value it behaves as though it
    chose. `construction` is `flat_rows` for all of them because that is what the builder
    makes; `feeling` is `cosy` because nothing in the record distinguishes one from another.
    """
    slug = design.slug
    return Concept(
        key=slug,
        title=design.title,
        # The premise is assembled from the only descriptive fields the design has. That it
        # reads as a product listing rather than an idea is the finding, not a flaw here.
        premise=(f"A {design.motif.replace('-', ' ')} motif worked in the "
                 f"{design.palette} palette across {design.width_stitches} stitches."),
        pod="home_decor",
        form=_match(slug, _FORM_HINTS, "flat_panel"),
        construction="flat_rows",
        motif=design.motif,
        palette_story=design.palette,
        recipient=_match(slug, _RECIPIENT_HINTS, "self"),
        occasion=_match(slug, _OCCASION_HINTS, "everyday"),
        feeling="cosy",
        # Empty on purpose: no design in the catalogue states what it does for its owner,
        # because the record has nowhere to say it.
        function="",
        make_lane="QUICK",
        provenance="generated by products/builder.py from motif + palette + width",
    )


def catalogue_concepts() -> list[Concept]:
    from ..products.builder import CATALOGUE

    return [concept_from_design(design) for design in CATALOGUE.values()]


def audit_catalogue() -> dict:
    """Run the creative gate against our own products and report what it finds.

    This is the measurement the owner's defect report deserves: not "creativity is low" but
    which critic fires, on how many products, and what in the generator produces it.
    """
    from .concept import Field, distance
    from .jury import Context, judge
    from .tournament import autopsy

    concepts = catalogue_concepts()
    field = Field(opportunity="existing generated catalogue", concepts=concepts)

    verdicts = []
    for concept in concepts:
        # Judged against the rest of the catalogue, which is the comparison that matters:
        # is this product a different idea from the others we already sell?
        others = [c for c in concepts if c.key != concept.key]
        verdicts.append(judge(concept, Context(catalogue=others, techniques=1)))

    rejected = [v for v in verdicts if not v.survives]
    from .tournament import Result, novelty, theme_fatigue

    result = Result(opportunity="existing generated catalogue",
                    at="", field_size=len(concepts), spread=field.spread(),
                    survivors=[v for v in verdicts if v.survives],
                    rejected=rejected, duplicate_pairs=field.duplicate_pairs())

    identical = [(a.key, b.key) for i, a in enumerate(concepts) for b in concepts[i + 1:]
                 if distance(a, b) == 0.0]

    return {
        "products_audited": len(concepts),
        "generator_degrees_of_freedom": generator_degrees_of_freedom(),
        "field_spread": field.spread(),
        "survivors": [v.concept for v in result.survivors],
        "rejected": len(rejected),
        "structurally_identical_pairs": identical,
        "autopsy": autopsy(result),
        # The two measures #94 names that nothing computed until now. Both read awkwardly
        # against this catalogue, which is the point of measuring rather than asserting.
        "theme_fatigue": theme_fatigue(concepts),
        "novelty": novelty(concepts),
        "root_cause": (
            "A `Design` in products/builder.py is a motif, a palette, a width and a repeat "
            "count. It has no field for recipient, occasion, function or construction, so "
            "every generated product is the same object in different decoration. The "
            "shortfall is not that the ideas are weak; the generator has no representation "
            "of an idea, so there is nothing for a creative standard to act on."),
        "what_would_fix_it": (
            "Generation has to start from a Concept — form, construction, recipient, "
            "occasion, function — and reach the motif last, rather than starting at the "
            "motif and never reaching the rest."),
    }


def generator_degrees_of_freedom() -> dict:
    """What the generator can actually vary, measured from the CIR it produces.

    Independent of every judgement made elsewhere in this module. The concept mapping above
    involves choices — which slug means which form, what a missing field defaults to — and a
    finding that rests on those choices is arguable. This one rests on compiling all eleven
    products and looking at what came out.
    """
    import collections

    from ..cir.model import Op, Repeat
    from ..products.builder import CATALOGUE, build

    def stitches(node, out: set) -> None:
        if isinstance(node, Op):
            out.add(node.stitch)
        elif isinstance(node, Repeat):
            for inner in node.ops:
                stitches(inner, out)

    constructions: collections.Counter = collections.Counter()
    components: collections.Counter = collections.Counter()
    vocabularies: collections.Counter = collections.Counter()
    for design in CATALOGUE.values():
        cir = build(design)
        for component in cir.components:
            constructions[component.construction] += 1
        components[len(cir.components)] += 1
        used: set = set()
        for component in cir.components:
            for row in component.rows:
                for node in row.ops:
                    stitches(node, used)
        vocabularies[tuple(sorted(used))] += 1

    return {
        "products": len(CATALOGUE),
        "constructions_used": dict(constructions),
        "components_per_product": {str(k): v for k, v in components.items()},
        "stitch_vocabularies": {",".join(k): v for k, v in vocabularies.items()},
        "varies": ["motif", "palette", "width", "repeat count"],
        "does_not_vary": ["construction", "component count", "stitch vocabulary",
                          "silhouette", "assembly", "shaping"],
        "finding": (
            "Every product is a single-component flat-rows panel worked in exactly two "
            "stitches. A garland, an ornament, a wall hanging, a table runner and a baby "
            "blanket are the same object at different widths. The names promise eleven "
            "products and the fabric delivers one."),
    }
