#!/usr/bin/env python3
"""Supply-chain verification, SBOM and change record for a release (F-158, F-416).

WHY. The lock (`requirements.lock`, generated by `scripts/lock_requirements.py`) pins every
distribution with sha256 hashes and the Dockerfile installs only it with `--require-hashes
--no-deps`. Three things were still missing: (1) nothing *verified* the lock's shape at
release time -- a hand edit that dropped a hash or added a `>=` line would only be caught by
pip inside the image build; (2) the material-change record was printed once at regeneration
and lived only in git history, not in release evidence; (3) there was no bill of materials
and nothing said, in a checkable form, what in the build is still unpinned (the base image tag
and the apt packages).

WHAT IT DOES (offline; reads files and git only, never the network)
  verify            lock: every requirement exact-pinned (`==`) with >=1 sha256 hash, no
                    duplicates, no bare/unhashed lines, every name in requirements.txt present;
                    Dockerfile: installs the lock with --require-hashes and --no-deps and no
                    other pip install; reports base-image digest pin and apt pins as findings.
                    Exit 1 on a lock or install-path problem; `--strict` also fails on findings.
  sbom              a CycloneDX-1.5-shaped JSON bill of materials from the lock (purl + hashes).
  diff --base REV   the change record: added / removed / version-changed / hash-changed
                    distributions between the lock at REV and the working-tree lock.
  evidence          everything above as one JSON document for a release record
                    (`ops/deploy_guard.py record` embeds it; `--base` defaults to the last
                    deployed SHA in release/DEPLOYED_HISTORY.json).

WHAT IT DOES NOT DO. It does not pin the base image or apt packages: the Dockerfile is on the
deploy path and changing it is a deploy decision (see the findings' `remedy`). It does not
build the image; that the image builds from the lock is proven only by a deploy.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "requirements.lock"
REQS = ROOT / "requirements.txt"
DOCKERFILE = ROOT / "Dockerfile"
HISTORY = ROOT / "release" / "DEPLOYED_HISTORY.json"

_REQ_START = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(\[[^\]]*\])?\s*(==|>=|<=|~=|!=|>|<|===)?\s*([^\s\\;]*)")
_HASH = re.compile(r"--hash=sha256:([0-9a-f]{64})\b")


def canon(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def parse_lock(text: str) -> tuple[dict, list[str]]:
    """{canon name: {"name", "version", "hashes"}} and the problems found."""
    entries: dict[str, dict] = {}
    problems: list[str] = []
    # Join backslash continuations into logical lines.
    logical, buf = [], ""
    for raw in text.splitlines():
        line = raw.split("#", 1)[0] if not raw.lstrip().startswith("--hash") else raw
        if raw.lstrip().startswith("#"):
            continue
        buf += " " + line.rstrip().rstrip("\\")
        if not raw.rstrip().endswith("\\"):
            if buf.strip():
                logical.append(buf.strip())
            buf = ""
    if buf.strip():
        logical.append(buf.strip())
    for line in logical:
        if line.startswith("-"):
            problems.append(f"option line in lock: {line[:60]!r}")
            continue
        m = _REQ_START.match(line)
        if not m:
            problems.append(f"unparseable lock line: {line[:60]!r}")
            continue
        name, op, ver = m.group(1), m.group(3), m.group(4)
        hashes = _HASH.findall(line)
        key = canon(name)
        if op != "==" or not ver or "*" in ver:
            problems.append(f"{name}: not exact-pinned ({op or 'no specifier'}{ver})")
        if not hashes:
            problems.append(f"{name}: no sha256 hash")
        if key in entries:
            problems.append(f"{name}: listed twice")
        entries[key] = {"name": name, "version": ver, "hashes": sorted(set(hashes))}
    if not entries:
        problems.append("the lock lists no distributions")
    return entries, problems


def requirement_names(text: str) -> list[str]:
    out = []
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line or line.startswith("-"):
            continue
        m = _REQ_START.match(line)
        if m:
            out.append(canon(m.group(1)))
    return out


def audit_dockerfile(text: str) -> tuple[list[str], list[dict]]:
    """(problems, findings). Problems break the hash-checked install path; findings are the
    parts of the build that are still not pinned."""
    problems: list[str] = []
    findings: list[dict] = []
    lines = [l.strip() for l in re.sub(r"\\\n", " ", text).splitlines()]
    froms = [l for l in lines if l.upper().startswith("FROM ")]
    if not froms:
        problems.append("Dockerfile has no FROM")
    for f in froms:
        image = f.split()[1]
        if "@sha256:" not in image:
            findings.append({
                "id": "base_image_not_digest_pinned", "severity": "medium",
                "detail": f"base image {image!r} is a mutable tag; a rebuild can pull different "
                          f"bytes than the suite ran on",
                "remedy": (f"replace `FROM {image}` with `FROM {image}@sha256:<digest>`, the "
                           f"digest from `docker buildx imagetools inspect {image}` on the day "
                           f"of the change (deploy-path change: integrator applies it with the "
                           f"next authorised deploy)")})
    pip_lines = [l for l in lines if re.search(r"\bpip3?\s+install\b", l)]
    lock_installs = [l for l in pip_lines if "requirements.lock" in l]
    if not lock_installs:
        problems.append("the Dockerfile does not install requirements.lock")
    for l in lock_installs:
        if "--require-hashes" not in l:
            problems.append("the lock is installed without --require-hashes")
        if "--no-deps" not in l:
            problems.append("the lock is installed without --no-deps")
    for l in pip_lines:
        if "requirements.lock" not in l:
            problems.append(f"a pip install outside the lock: {l[:80]!r}")
    if not any(re.match(r"COPY\s+.*requirements\.lock", l) for l in lines):
        problems.append("the Dockerfile does not copy requirements.lock")
    for l in lines:
        if re.search(r"\b(curl|wget)\b[^|]*\|\s*(ba)?sh\b", l):
            problems.append(f"pipes a download into a shell: {l[:80]!r}")
        m = re.search(r"apt-get install\s+(.*?)(?:&&|$)", l)
        if m:
            pkgs = [p for p in m.group(1).split() if not p.startswith("-")]
            unpinned = [p for p in pkgs if "=" not in p]
            if unpinned:
                findings.append({
                    "id": "apt_packages_unpinned", "severity": "low",
                    "detail": f"apt packages without a version: {', '.join(unpinned)}",
                    "remedy": ("pin as `pkg=<version>` from the base image's archive, or accept "
                               "with a recorded reason (fonts only; no code executes from them)")})
    return problems, findings


def sbom(entries: dict, *, lock_sha256: str) -> dict:
    comps = []
    for key in sorted(entries):
        e = entries[key]
        comps.append({"type": "library", "name": e["name"], "version": e["version"],
                      "purl": f"pkg:pypi/{key}@{e['version']}",
                      "hashes": [{"alg": "SHA-256", "content": h} for h in e["hashes"]]})
    return {"bomFormat": "CycloneDX", "specVersion": "1.5", "version": 1,
            "metadata": {"component": {"type": "application", "name": "brambleloop"},
                         "properties": [{"name": "brambleloop:lock_sha256",
                                         "value": lock_sha256}],
                         "tools": [{"name": "brambleloop/scripts/supply_chain.py"}]},
            "components": comps}


def change_record(old: dict, new: dict) -> dict:
    added = sorted(f"{new[k]['name']}=={new[k]['version']}" for k in new.keys() - old.keys())
    removed = sorted(f"{old[k]['name']}=={old[k]['version']}" for k in old.keys() - new.keys())
    changed, rehashed = [], []
    for k in sorted(old.keys() & new.keys()):
        if old[k]["version"] != new[k]["version"]:
            changed.append(f"{new[k]['name']}: {old[k]['version']} -> {new[k]['version']}")
        elif old[k]["hashes"] != new[k]["hashes"]:
            rehashed.append(new[k]["name"])
    return {"added": added, "removed": removed, "version_changed": changed,
            "hash_changed_same_version": rehashed,
            "material": bool(added or removed or changed or rehashed)}


def lock_at(rev: str, *, root: Path = ROOT) -> str | None:
    rel = (root / "requirements.lock").relative_to(_git_top(root)).as_posix()
    p = subprocess.run(["git", "-C", str(root), "show", f"{rev}:{rel}"],
                       capture_output=True, text=True)
    return p.stdout if p.returncode == 0 else None


def _git_top(root: Path) -> Path:
    p = subprocess.run(["git", "-C", str(root), "rev-parse", "--show-toplevel"],
                       capture_output=True, text=True)
    return Path(p.stdout.strip()) if p.returncode == 0 else root


def last_deployed(history: Path = HISTORY) -> str | None:
    try:
        dep = json.loads(history.read_text()).get("deployed") or []
    except (OSError, ValueError):
        return None
    return dep[-1].get("sha") if dep else None


def verify(*, lock_text: str, reqs_text: str, docker_text: str) -> dict:
    entries, problems = parse_lock(lock_text)
    missing = [n for n in requirement_names(reqs_text) if n not in entries]
    problems += [f"{n}: in requirements.txt but not in the lock" for n in missing]
    dprob, findings = audit_dockerfile(docker_text)
    problems += dprob
    return {"ok": not problems, "problems": problems, "findings": findings,
            "distributions": len(entries),
            "hashes": sum(len(e["hashes"]) for e in entries.values()),
            "lock_sha256": hashlib.sha256(lock_text.encode()).hexdigest(),
            "_entries": entries}


def evidence(*, base: str | None = None, root: Path = ROOT) -> dict:
    lock_text = (root / "requirements.lock").read_text()
    v = verify(lock_text=lock_text, reqs_text=(root / "requirements.txt").read_text(),
               docker_text=(root / "Dockerfile").read_text())
    entries = v.pop("_entries")
    bom = sbom(entries, lock_sha256=v["lock_sha256"])
    bom_bytes = json.dumps(bom, sort_keys=True).encode()
    base = base or last_deployed(root / "release" / "DEPLOYED_HISTORY.json")
    change = None
    if base:
        old_text = lock_at(base, root=root)
        known = subprocess.run(["git", "-C", str(root), "cat-file", "-e", f"{base}^{{commit}}"],
                               capture_output=True).returncode == 0
        if old_text is not None:
            change = {"base": base, "base_had_lock": True,
                      **change_record(parse_lock(old_text)[0], entries)}
        elif known:
            # The base predates the lock (production fcb982d installed requirements.txt lower
            # bounds): relative to it, every pinned distribution is a material change.
            change = {"base": base, "base_had_lock": False,
                      **change_record({}, entries),
                      "note": "the base installed from requirements.txt lower bounds, unhashed; "
                              "the first lock-installed image changes every distribution"}
        else:
            change = {"base": base, "error": "the base revision is not in this repository"}
    return {"kind": "brambleloop.supply_chain", "version": 1, **v,
            "sbom_sha256": hashlib.sha256(bom_bytes).hexdigest(),
            "sbom_components": len(bom["components"]),
            "change_since_base": change,
            "limits": ["offline: hashes are those the lock pins, not re-fetched",
                       "the image build from the lock is proven only by a deploy"]}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    vp = sub.add_parser("verify")
    vp.add_argument("--strict", action="store_true")
    sp = sub.add_parser("sbom")
    sp.add_argument("--out")
    dp = sub.add_parser("diff")
    dp.add_argument("--base", required=True)
    ep = sub.add_parser("evidence")
    ep.add_argument("--base")
    ep.add_argument("--out")
    a = ap.parse_args(argv)
    if a.cmd == "verify":
        v = verify(lock_text=LOCK.read_text(), reqs_text=REQS.read_text(),
                   docker_text=DOCKERFILE.read_text())
        v.pop("_entries")
        print(json.dumps(v, indent=2))
        return 0 if v["ok"] and not (a.strict and v["findings"]) else 1
    if a.cmd == "sbom":
        text = LOCK.read_text()
        entries, problems = parse_lock(text)
        bom = sbom(entries, lock_sha256=hashlib.sha256(text.encode()).hexdigest())
        out = json.dumps(bom, indent=2, sort_keys=True) + "\n"
        if a.out:
            Path(a.out).write_text(out)
        else:
            print(out, end="")
        return 1 if problems else 0
    if a.cmd == "diff":
        old = lock_at(a.base)
        if old is None:
            print(f"the lock is not readable at {a.base}")
            return 2
        print(json.dumps(change_record(parse_lock(old)[0], parse_lock(LOCK.read_text())[0]),
                         indent=2))
        return 0
    ev = evidence(base=a.base)
    out = json.dumps(ev, indent=2, sort_keys=True) + "\n"
    if a.out:
        Path(a.out).write_text(out)
    else:
        print(out, end="")
    return 0 if ev["ok"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
